import { useState } from 'react'

async function buildPdf(data) {
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF()
  const margin = 18
  let y = margin
  const pageWidth = doc.internal.pageSize.getWidth()
  const maxWidth = pageWidth - margin * 2

  // Header band
  doc.setFillColor(11, 18, 32) // #0B1220
  doc.rect(0, 0, pageWidth, 30, 'F')
  doc.setTextColor(255, 176, 32) // amber
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.text('SEO Rig — Diagnostic Report', margin, 18)
  doc.setFontSize(9)
  doc.setTextColor(180, 180, 180)
  doc.text(new Date().toLocaleDateString(), pageWidth - margin, 18, { align: 'right' })
  y = 42

  doc.setTextColor(20, 20, 20)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.text('Page audited:', margin, y)
  doc.setFont('helvetica', 'normal')
  doc.text(data.url, margin + 30, y)
  y += 10

  // Score
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(28)
  const scoreColor = data.score >= 80 ? [52, 211, 153] : data.score >= 50 ? [255, 176, 32] : [248, 113, 113]
  doc.setTextColor(...scoreColor)
  doc.text(`${data.score}/100`, margin, y + 12)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(100, 100, 100)
  doc.text('Overall SEO Score', margin, y + 19)
  y += 30

  function sectionTitle(text) {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(12)
    doc.setTextColor(20, 20, 20)
    doc.text(text, margin, y)
    doc.setDrawColor(230, 230, 230)
    doc.line(margin, y + 2, pageWidth - margin, y + 2)
    y += 9
  }

  function checkPageBreak(needed = 10) {
    if (y + needed > 280) { doc.addPage(); y = margin }
  }

  sectionTitle('Page Basics')
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9.5)
  doc.setTextColor(60, 60, 60)
  const basics = [
    [`Title (${data.titleLength} chars)`, data.title || '(missing)'],
    [`Meta description (${data.metaDescriptionLength} chars)`, data.metaDescription || '(missing)'],
    ['Word count', String(data.wordCount)],
    ['H1 tags', String(data.headings.h1.length)],
    ['Images missing alt text', `${data.imagesMissingAlt} / ${data.totalImages}`],
    ['Internal / external links', `${data.internalLinks} / ${data.externalLinks}`],
  ]
  basics.forEach(([label, val]) => {
    checkPageBreak(12)
    doc.setFont('helvetica', 'bold')
    doc.text(label + ':', margin, y)
    doc.setFont('helvetica', 'normal')
    const lines = doc.splitTextToSize(String(val), maxWidth - 55)
    doc.text(lines, margin + 55, y)
    y += 6 * lines.length + 1
  })
  y += 4

  checkPageBreak(20)
  sectionTitle(`Issues Found (${data.issues.length})`)
  doc.setFontSize(9.5)
  if (data.issues.length === 0) {
    doc.setTextColor(52, 150, 100)
    doc.text('No issues found.', margin, y)
    y += 7
  } else {
    data.issues.forEach(issue => {
      checkPageBreak(8)
      doc.setTextColor(issue.severity === 'error' ? 200 : 150, issue.severity === 'error' ? 60 : 120, 60)
      const lines = doc.splitTextToSize('• ' + issue.msg, maxWidth)
      doc.text(lines, margin, y)
      y += 6 * lines.length
    })
  }
  y += 4

  checkPageBreak(20)
  sectionTitle(`Passing Checks (${data.passes.length})`)
  doc.setFontSize(9.5)
  doc.setTextColor(50, 50, 50)
  data.passes.forEach(p => {
    checkPageBreak(8)
    const lines = doc.splitTextToSize('✓ ' + p, maxWidth)
    doc.text(lines, margin, y)
    y += 6 * lines.length
  })

  // Footer on last page
  doc.setFontSize(8)
  doc.setTextColor(150, 150, 150)
  doc.text('Generated by SEO Rig — Diagnostic Suite', margin, 292)

  return doc
}

export default function ReportGenerator() {
  const [url, setUrl] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)
  const [data, setData] = useState(null)

  async function runAndFetch(e) {
    e.preventDefault()
    if (!url.trim()) return
    setLoading(true)
    setError(null)
    setData(null)
    try {
      const res = await fetch(`/api/analyze?url=${encodeURIComponent(url.trim())}`)
      const json = await res.json()
      if (!res.ok) throw new Error(json.error || 'Something went wrong')
      setData(json)
    } catch (err) {
      setError(err.message)
    } finally {
      setLoading(false)
    }
  }

  const [generating, setGenerating] = useState(false)

  async function downloadPdf() {
    setGenerating(true)
    try {
      const doc = await buildPdf(data)
      const filename = `seo-report-${new URL(data.url).hostname}.pdf`
      doc.save(filename)
    } finally {
      setGenerating(false)
    }
  }

  return (
    <div className="max-w-3xl">
      <div className="mb-6">
        <h1 className="text-2xl font-semibold text-white" style={{fontFamily:'Space Grotesk, sans-serif'}}>Report Generator</h1>
        <p className="text-[#9CA3AF] text-sm mt-1">Runs a full on-page audit, then compiles it into a branded PDF you can send to a client.</p>
      </div>

      <form onSubmit={runAndFetch} className="flex gap-2 mb-6">
        <input
          value={url}
          onChange={e => setUrl(e.target.value)}
          placeholder="kaagazpdf.in or https://example.com/page"
          className="flex-1 bg-[#141B2D] border border-white/10 rounded-lg px-4 py-2.5 text-sm text-[#E8ECF4] placeholder-[#4B5563] focus:outline-none focus:border-[#FFB020]/50 font-mono"
        />
        <button
          type="submit"
          disabled={loading}
          className="bg-[#FFB020] text-[#0B1220] font-medium text-sm px-5 py-2.5 rounded-lg hover:bg-[#ffc04d] transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {loading ? 'Auditing…' : 'Run Audit'}
        </button>
      </form>

      {error && <div className="bg-[#F87171]/10 border border-[#F87171]/30 rounded-lg px-4 py-3 text-sm text-[#F87171] mb-6">{error}</div>}

      {loading && (
        <div className="flex items-center gap-2 text-[#9CA3AF] text-sm font-mono">
          <span className="w-2 h-2 rounded-full bg-[#FFB020] animate-pulse" /> running audit…
        </div>
      )}

      {data && (
        <div className="bg-[#141B2D] border border-white/10 rounded-lg p-6">
          <div className="flex items-center justify-between mb-4">
            <div>
              <div className="text-white font-medium">{data.url}</div>
              <div className="text-sm text-[#9CA3AF] mt-1">Score: <span className="font-mono text-[#FFB020]">{data.score}/100</span> · {data.issues.length} issues · {data.passes.length} passing</div>
            </div>
          </div>
          <button
            onClick={downloadPdf}
            disabled={generating}
            className="bg-[#FFB020] text-[#0B1220] font-medium text-sm px-5 py-2.5 rounded-lg hover:bg-[#ffc04d] transition-colors disabled:opacity-50"
          >
            {generating ? 'Building PDF…' : '↓ Download PDF Report'}
          </button>
        </div>
      )}
    </div>
  )
}
